server:
  port: 8888

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}

spring:
  application:
    name: configserver
